config/routes.rb
Rails.application.routes.draw do
  resources :image_comments
  resources :images
  root 'static_pages#home'

  devise_for :users
  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :file , ImageUploader
    belongs_to :user
    has_many :image_comment, -> { order "created_at DESC"}
end

app/models/image_comment.rb
class ImageComment < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # サインインしているユーザーのみ、アクションにアクセス可能にする
  # before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
  # sign_upのときに、name, ageを許可する
  devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age]
  
  # account_updateのときに、name,ageを許可する
  devise_parameter_sanitizer.permit :account_update, keys: [:name, :age]
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  # サインインしているユーザーのみ、アクションにアクセス可能にする
  before_action :authenticate_user!
  
  
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :number_of_pages)
    end
end

app/controllers/image_comments_controller.rb
class ImageCommentsController < ApplicationController
  before_action :set_image_comment, only: [:show, :edit, :update, :destroy]

  # GET /image_comments
  # GET /image_comments.json
  def index
    @image_comments = ImageComment.all
  end

  # GET /image_comments/1
  # GET /image_comments/1.json
  def show
  end

  # GET /image_comments/new
  def new
    @image_comment = ImageComment.new
  end

  # GET /image_comments/1/edit
  def edit
  end

  # POST /image_comments
  # POST /image_comments.json
  def create
    @image_comment = ImageComment.new(image_comment_params)
    @image_comment.user_id = current_user.id
    respond_to do |format|
      if @image_comment.save
        url = "/images/" + @image_comment.image_id.to_s
        format.html { redirect_to url, notice: 'Image comment was successfully created.' }
        # format.html { redirect_to @image_comment, notice: 'Image comment was successfully created.' }
        format.json { render :show, status: :created, location: @image_comment }
      else
        format.html { render :new }
        format.json { render json: @image_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_comments/1
  # PATCH/PUT /image_comments/1.json
  def update
    respond_to do |format|
      if @image_comment.update(image_comment_params)
        format.html { redirect_to @image_comment, notice: 'Image comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_comment }
      else
        format.html { render :edit }
        format.json { render json: @image_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_comments/1
  # DELETE /image_comments/1.json
  def destroy
    @image_comment.destroy
    respond_to do |format|
      format.html { redirect_to image_comments_url, notice: 'Image comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_comment
      @image_comment = ImageComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_comment_params
      params.require(:image_comment).permit(:user_id, :image_id, :comment)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image_comment = ImageComment.new
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id
    
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:user_id, :title, :file, :created_at)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/image_comments_helper.rb
module ImageCommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :number_of_pages %><br>
    <%= f.number_field :number_of_pages %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Number of pages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.number_of_pages %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Number of pages:</strong>
  <%= @book.number_of_pages %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/image_comments/_form.html.erb
<%= form_for(@image_comment) do |f| %>
  <% if @image_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image_comment.errors.count, "error") %> prohibited this image_comment from being saved:</h2>

      <ul>
      <% @image_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image_id %><br>
    <%= f.number_field :image_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/image_comments/edit.html.erb
<h1>Editing Image Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @image_comment %> |
<%= link_to 'Back', image_comments_path %>

app/views/image_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Image Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_comments.each do |image_comment| %>
      <tr>
        <td><%= image_comment.user_id %></td>
        <td><%= image_comment.image_id %></td>
        <td><%= image_comment.comment %></td>
        <td><%= link_to 'Show', image_comment %></td>
        <td><%= link_to 'Edit', edit_image_comment_path(image_comment) %></td>
        <td><%= link_to 'Destroy', image_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image comment', new_image_comment_path %>

app/views/image_comments/new.html.erb
<h1>New Image Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', image_comments_path %>

app/views/image_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @image_comment.user_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @image_comment.image_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @image_comment.comment %>
</p>

<%= link_to 'Edit', edit_image_comment_path(@image_comment) %> |
<%= link_to 'Back', image_comments_path %>

app/views/images/_form.html.erb
<%= form_for(@image, {multipart: true}) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>File</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.user_id %></td>
        <td><%= image.title %></td>
        <td><%= image_tag image.file %></td>
        <td><%= image.created_at %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @image.user.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>File:</strong>
  <%= image_tag @image.file %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @image.created_at %>
</p>
<h2>コメントフォーム</h2>
  <%= form_for(@image_comment) do |f| %>
  <div class= "field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
    <%= f.hidden_field :image_id, :value => @image.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
</div>
<% end %>
<h2>コメント一覧</h2>
<ul>
  <% @image.image_comment.each do |image_comment|%>
    <li><%= image_comment.comment %>
    (<i><%= image_comment.user.name %></i>)</li>
  <% end %>
</ul>
<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
<h3>Hello, <%= current_user.email %>!!!!!!!!!!!!!!</h3>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign in", new_user_session_path %>
<%= link_to "Sign up", new_user_registration_path %>
<% end %>
<hr>
<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>Anh Hùng AVENGERS sẽ làm gì khi kết thúc phần 4 :)))</h1>
<h3></h3>
<img width='400px' src="https://scontent.fsgn2-2.fna.fbcdn.net/v/t1.0-9/54518222_1201491853353700_7454538821703565312_n.jpg?_nc_cat=102&_nc_oc=AQmejselPrxR-nf4pFyohHMq0-27fcMSU9DC5TywcgVsDGGyTDkBJzbkV6bXluvThqY&_nc_ht=scontent.fsgn2-2.fna&oh=05ce4b299361d2bd6fcfc5a9b3b47109&oe=5D19DC10"/>